name: ShopAddonStripped

main: me.tWizT3d_dreaMr.ShopAddonStripped.main
version: 1.0.0
author: tWizT3d_dreaMr
api-version: 1.19
commands:
   filterall:
      description: filterall shops
      usage: filterall